#+TITLE: =emacs-input-display= - Live lossage preview

This repository will contain a basic input display meant for enhancing streams
and screencasts using Emacs.

The name is temporary for now. I will have to come up with something better.

While other similar tools exist, this one is just made by me to have a coding
stream.

* How to use
1. Install this package with a package manager of your choice or load
   =emacs-input-display.el=.
2. =M-x emacs-input-display=

A frame with recent outputs will pop up. Feel free to add an OBS capture for
it, crop and chroma key it to your liking. The title is intentionally static
to make it easy to have it work reliably.

* Things to do (remove once done)
** TODO come up with a better name
The current one doesn't have a nice ring to it, and contains the word Emacs,
which would be a redundant word in a feature name.

** DONE bury the new frame when it's created
This might not work in every window manager:

From [[info:elisp#Raising and Lowering][elisp#Raising and Lowering]]:
#+begin_quote
Some window managers may refuse to restack windows.
#+end_quote
